var buf = new Buffer('Salut', 'utf8');
console.log(buf);
console.log(buf.toString());
console.log(buf.toJSON());
console.log(buf[2]);
buf.write('wo');
console.log(buf.toString());
console.log(buf.toString());
console.log(buf.toString());
console.log(`Donc: ${buf.toString()}`);